Repository everypolitician/commons-api, pull requests merged in 2019-01, with the labels that each got.

#19 Legislative districts
  commons_api/wikidata/admin.py
  commons_api/wikidata/managers.py
  commons_api/wikidata/migrations/0005_seat_and_district_counts.py
  commons_api/wikidata/models.py
  commons_api/wikidata/tasks/legislature.py
  commons_api/wikidata/templates/wikidata/country_detail.html
  commons_api/wikidata/templates/wikidata/legislativehouse_detail.html
  commons_api/wikidata/templates/wikidata/legislativehouse_membership.html
  commons_api/wikidata/templates/wikidata/query/legislature_constituencies.rq
  commons_api/wikidata/templates/wikidata/query/legislature_list.rq
  commons_api/wikidata/templates/wikidata/query/legislature_memberships.rq
  commons_api/wikidata/urls.py
  commons_api/wikidata/views.py
Labels: review

#5 [WiP] Add geometry fields for admin areas and electoral districts
  Procfile
  app.json
  commons_api/proto_commons/__init__.py
  commons_api/proto_commons/admin.py
  commons_api/proto_commons/migrations/0001_initial.py
  commons_api/proto_commons/migrations/__init__.py
  commons_api/proto_commons/models.py
  commons_api/proto_commons/tasks/__init__.py
  commons_api/proto_commons/tasks/boundaries.py
  commons_api/settings.py
  commons_api/urls.py
  commons_api/wikidata/admin.py
  commons_api/wikidata/migrations/0006_country_iso_3166_1_code.py
  commons_api/wikidata/migrations/0007_add_boundary_foreignkeys.py
  commons_api/wikidata/models.py
  commons_api/wikidata/tasks/__init__.py
  commons_api/wikidata/tasks/country.py
  commons_api/wikidata/templates/wikidata/country_detail.html
  commons_api/wikidata/templates/wikidata/country_list.html
  commons_api/wikidata/templates/wikidata/query/country_list.rq
  commons_api/wikidata/views.py
  requirements.txt
Labels: enhancement, review

#28 Queue status
  commons_api/settings.py
  commons_api/templates/base.html
  commons_api/templates/commons_api/queue-status.html
  commons_api/urls.py
  commons_api/views.py
  commons_api/wikidata/models.py
  requirements.txt
Labels: enhancement

#32 Add a GeoJSON renderer, and spatial API endpoints
  .travis.yml
  commons_api/settings.py
  commons_api/templates/base.html
  commons_api/wikidata/api.py
  commons_api/wikidata/renderers.py
  commons_api/wikidata/serializers.py
  commons_api/wikidata/tests/__init__.py
  commons_api/wikidata/tests/geojson.py
  commons_api/wikidata/tests/serializers.py
  commons_api/wikidata/urls.py
  commons_api/wikidata/viewsets.py
  requirements.txt
Labels: review

#34 Popolo JSON renderer
  commons_api/wikidata/api.py
  commons_api/wikidata/models.py
  commons_api/wikidata/renderers.py
  commons_api/wikidata/serializers.py
  commons_api/wikidata/views.py
  commons_api/wikidata/viewsets.py
Labels: review

#36 Change default sparql query from GET to POST
  commons_api/wikidata/tests/__init__.py
  commons_api/wikidata/tests/utils.py
  commons_api/wikidata/utils.py
Labels: review
